export const GET_MY_POKEMON = 'GET_MY_POKEMON';
export const GET_POKEMON = 'GET_POKEMON';
export const ADD_MY_POKEMON = 'ADD_MY_POKEMON';
export const DELETE_MY_POKEMON = 'DELETE_MY_POKEMON';
export const UPDATE_TOOLBAR = 'UPDATE_TOOLBAR';
export const RESET_POKEMON = 'RESET_POKEMON';
